// Result actionTypes

export const RESULT_GET_DATA = "RESULT_GET_DATA";
export const RESULT_SET_DATA = "RESULT_SET_DATA";
export const RESULT_FAIL_DATA = "RESULT_FAIL_DATA";
export const DELETE_RESULT_FAIL = "DELETE_RESULT_FAIL";
export const POST_RESULT_DATA = "POST_RESULT_DATA";
export const POST_RESULT_DATA_START = "POST_RESULT_DATA_START";
export const POST_RESULT_DATA_FAIL = "POST_RESULT_DATA_FAIL";
export const POST_RESULT_DATA_SUCCESS = "POST_RESULT_DATA_SUCCESS";

export const UPDATE_RESULT_DATA_START = "UPDATE_RESULT_DATA_START";
export const RESULT_LOADING = "RESULT_LOADING";
export const RESULT_EDIT_SET_DATA = "RESULT_EDIT_SET_DATA";
export const RESULT_EDIT_FAIL_DATA = "RESULT_EDIT_FAIL_DATA";
